#!/usr/bin/env bash
# Install monitoring services. Idempotent — re-run safely. Run as root.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
PY=/usr/bin/python3
COMPOSE_DIR=$(dirname "$ROOT")  # /srv/Container

# Detect what's available on this host (collectors skip themselves at runtime,
# but we don't even create units for things that can't possibly work)
HAS_GPU=0; command -v nvidia-smi >/dev/null && HAS_GPU=1
HAS_DOCKER=0; command -v docker >/dev/null && HAS_DOCKER=1
HAS_GDB=0; command -v gdb >/dev/null && HAS_GDB=1

echo "host detection: GPU=$HAS_GPU docker=$HAS_DOCKER gdb=$HAS_GDB"

# First-run: create config.toml from template if it doesn't exist yet,
# then prompt the operator to set host_id.
if [[ ! -f "$ROOT/config.toml" && -f "$ROOT/config.example.toml" ]]; then
  cp "$ROOT/config.example.toml" "$ROOT/config.toml"
  sed -i "s/<set-per-host>/$(hostname -s)/" "$ROOT/config.toml"
  echo "  created $ROOT/config.toml from template (host_id=$(hostname -s))"
fi

# Initialize DB schema
"$PY" "$ROOT/db.py"

# Allow stall_detect to run gdb + read /proc/<pid>/stack without password.
# Keep it tight: only the two commands we actually call.
SUDOERS=/etc/sudoers.d/ollama-monitor
cat > "$SUDOERS" <<EOF
# Generated by /srv/Container/monitoring/install.sh — allows stall_detect.py
# to capture diagnostic info from the host-side ollama PID without password.
root ALL=(root) NOPASSWD: /usr/bin/gdb -batch -nx -ex set pagination off -ex thread apply all bt -p *
root ALL=(root) NOPASSWD: /usr/bin/timeout 15 /usr/bin/gdb *
root ALL=(root) NOPASSWD: /usr/bin/head -50 /proc/*
EOF
chmod 440 "$SUDOERS"
visudo -c -f "$SUDOERS" >/dev/null

# Service factory
make_unit() {
  local name="$1" desc="$2" entrypoint="$3" workdir="$4" requires_docker="$5"
  local path=/etc/systemd/system/${name}.service
  cat > "$path" <<EOF
[Unit]
Description=$desc
After=network.target${requires_docker:+ docker.service}
${requires_docker:+Requires=docker.service}

[Service]
Type=simple
ExecStart=$PY $entrypoint
WorkingDirectory=$workdir
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=$name

[Install]
WantedBy=multi-user.target
EOF
  echo "  wrote $path"
}

# Build unit set based on available capabilities
UNITS=()

if [[ $HAS_GPU -eq 1 ]]; then
  make_unit "ollama-gpu-logger" "Ollama GPU metrics collector" \
    "$ROOT/collectors/gpu.py" "$ROOT" ""
  UNITS+=(ollama-gpu-logger)
fi

if [[ $HAS_DOCKER -eq 1 ]]; then
  make_unit "ollama-log-parser" "Ollama docker-log parser" \
    "$ROOT/collectors/ollama_logs.py" "$COMPOSE_DIR" "yes"
  UNITS+=(ollama-log-parser)

  make_unit "ollama-process-logger" "Ollama process metrics collector" \
    "$ROOT/collectors/process.py" "$ROOT" "yes"
  UNITS+=(ollama-process-logger)

  if [[ $HAS_GPU -eq 1 ]]; then
    make_unit "ollama-stall-detector" "Ollama stall detector with stack capture" \
      "$ROOT/collectors/stall_detect.py" "$ROOT" "yes"
    UNITS+=(ollama-stall-detector)
  fi
fi

make_unit "ollama-dashboard" "Ollama monitoring dashboard + REST API" \
  "$ROOT/api/serve.py" "$ROOT" ""
UNITS+=(ollama-dashboard)

systemctl daemon-reload
for u in "${UNITS[@]}"; do
  systemctl enable "${u}.service" >/dev/null 2>&1
  systemctl restart "${u}.service"
  echo "  enabled+restarted $u"
done

# Retention cron — extend to clean stalls/ dir too
cat > /etc/cron.d/ollama-monitor-retention <<'EOF'
# Monitoring data retention (30 days). Removes old DB rows + stack dumps.
0 3 * * * root /usr/bin/python3 -c "
import sqlite3, pathlib, time
conn = sqlite3.connect('/srv/Container/monitoring/monitor.db')
for t in ('gpu_metrics', 'ollama_requests', 'system_metrics'):
    conn.execute(f\"DELETE FROM {t} WHERE timestamp < datetime('now', '-30 days')\")
conn.execute(\"DELETE FROM stall_events WHERE start_ts < datetime('now', '-30 days')\")
conn.execute('VACUUM'); conn.close()
cutoff = time.time() - 30*86400
for p in pathlib.Path('/srv/Container/monitoring/stalls').glob('*.txt'):
    if p.stat().st_mtime < cutoff: p.unlink()
" >> /var/log/ollama-monitor-retention.log 2>&1
EOF
chmod 644 /etc/cron.d/ollama-monitor-retention
echo "  retention cron installed"

mkdir -p "$ROOT/stalls"
chmod 755 "$ROOT/stalls"

echo ""
echo "Done. Services:"
for u in "${UNITS[@]}"; do
  systemctl is-active --quiet "$u" && echo "  ✓ $u" || echo "  ✗ $u (check journalctl -u $u)"
done
echo ""
echo "Dashboard: http://$(hostname -I | awk '{print $1}'):${PORT:-3002}/"
