#!/usr/bin/env bash
# Install monitoring services. Idempotent — re-run safely. Run as root.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
PY=/usr/bin/python3
COMPOSE_DIR=$(dirname "$ROOT")  # /srv/Container

# Detect what's available on this host (collectors skip themselves at runtime,
# but we don't even create units for things that can't possibly work)
HAS_GPU=0; command -v nvidia-smi >/dev/null && HAS_GPU=1
HAS_DOCKER=0; command -v docker >/dev/null && HAS_DOCKER=1
HAS_GDB=0; command -v gdb >/dev/null && HAS_GDB=1

echo "host detection: GPU=$HAS_GPU docker=$HAS_DOCKER gdb=$HAS_GDB"

# First-run: create config.toml from template if it doesn't exist yet,
# then prompt the operator to set host_id.
if [[ ! -f "$ROOT/config.toml" && -f "$ROOT/config.example.toml" ]]; then
  cp "$ROOT/config.example.toml" "$ROOT/config.toml"
  sed -i "s/<set-per-host>/$(hostname -s)/" "$ROOT/config.toml"
  echo "  created $ROOT/config.toml from template (host_id=$(hostname -s))"
fi

# Initialize DB schema
"$PY" "$ROOT/db.py"

# Allow stall_detect to run gdb + read /proc/<pid>/stack without password.
# Keep it tight: only the two commands we actually call.
SUDOERS=/etc/sudoers.d/ollama-monitor
cat > "$SUDOERS" <<EOF
# Generated by /srv/Container/monitoring/install.sh — allows stall_detect.py
# to capture diagnostic info from the host-side ollama PID without password.
root ALL=(root) NOPASSWD: /usr/bin/gdb -batch -nx -ex set pagination off -ex thread apply all bt -p *
root ALL=(root) NOPASSWD: /usr/bin/timeout 15 /usr/bin/gdb *
root ALL=(root) NOPASSWD: /usr/bin/head -50 /proc/*
EOF
chmod 440 "$SUDOERS"
visudo -c -f "$SUDOERS" >/dev/null

# Service factory
make_unit() {
  local name="$1" desc="$2" entrypoint="$3" workdir="$4" requires_docker="$5"
  local path=/etc/systemd/system/${name}.service
  cat > "$path" <<EOF
[Unit]
Description=$desc
After=network.target${requires_docker:+ docker.service}
${requires_docker:+Requires=docker.service}

[Service]
Type=simple
ExecStart=$PY $entrypoint
WorkingDirectory=$workdir
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=$name

[Install]
WantedBy=multi-user.target
EOF
  echo "  wrote $path"
}

# Build unit set based on available capabilities
UNITS=()

if [[ $HAS_GPU -eq 1 ]]; then
  make_unit "ollama-gpu-logger" "Ollama GPU metrics collector" \
    "$ROOT/collectors/gpu.py" "$ROOT" ""
  UNITS+=(ollama-gpu-logger)
fi

if [[ $HAS_DOCKER -eq 1 ]]; then
  make_unit "ollama-log-parser" "Ollama docker-log parser" \
    "$ROOT/collectors/ollama_logs.py" "$COMPOSE_DIR" "yes"
  UNITS+=(ollama-log-parser)

  make_unit "ollama-process-logger" "Ollama process metrics collector" \
    "$ROOT/collectors/process.py" "$ROOT" "yes"
  UNITS+=(ollama-process-logger)

  if [[ $HAS_GPU -eq 1 ]]; then
    make_unit "ollama-stall-detector" "Ollama stall detector with stack capture" \
      "$ROOT/collectors/stall_detect.py" "$ROOT" "yes"
    UNITS+=(ollama-stall-detector)
  fi
fi

make_unit "ollama-dashboard" "Ollama monitoring dashboard + REST API" \
  "$ROOT/api/serve.py" "$ROOT" ""
UNITS+=(ollama-dashboard)

systemctl daemon-reload
for u in "${UNITS[@]}"; do
  systemctl enable "${u}.service" >/dev/null 2>&1
  systemctl restart "${u}.service"
  echo "  enabled+restarted $u"
done

# Tiered retention — systemd timer, NOT cron.
#
# The previous version of this block wrote a MULTI-LINE command into
# /etc/cron.d. The crontab format has no line continuation: every line is its
# own entry, so the job was never handed to a shell and never ran once — on
# ti-30 that went unnoticed for 146 days. It was provable after the fact
# because the command's `>> …log` redirect would have created the log file even
# if the command itself had failed, and that file never existed.
#
# Two consequences, both deliberate:
#   1. the work lives in retention.py and the unit just calls it, so nothing
#      depends on quoting survivng a crontab parser;
#   2. every run writes a row into maintenance_log, and stack_check.py fails
#      if the newest row is older than 25 h. A job that stops running now says so.
rm -f /etc/cron.d/ollama-monitor-retention

cat > /etc/systemd/system/ollama-monitor-retention.service <<EOF
[Unit]
Description=Ollama monitoring: tiered retention (downsample + prune)
After=network.target

[Service]
Type=oneshot
ExecStart=$PY $ROOT/retention.py
WorkingDirectory=$ROOT
StandardOutput=journal
StandardError=journal
SyslogIdentifier=ollama-monitor-retention
EOF

cat > /etc/systemd/system/ollama-monitor-retention.timer <<'EOF'
[Unit]
Description=Ollama monitoring: run tiered retention daily

[Timer]
OnCalendar=*-*-* 03:17:00
Persistent=true
RandomizedDelaySec=300

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now ollama-monitor-retention.timer >/dev/null 2>&1
echo "  retention timer installed (systemd, daily 03:17)"

mkdir -p "$ROOT/stalls"
chmod 755 "$ROOT/stalls"

echo ""
echo "Done. Services:"
for u in "${UNITS[@]}"; do
  systemctl is-active --quiet "$u" && echo "  ✓ $u" || echo "  ✗ $u (check journalctl -u $u)"
done
echo ""
echo "Dashboard: http://$(hostname -I | awk '{print $1}'):${PORT:-3002}/"
